project:
  type: website

website:
  title: "ISSS608 VAA (Wilson)"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - sidebar:handson
      - sidebar:inclass
      - sidebar:takehome
  sidebar:
    - id: handson
      title: "Hands-on Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        href: hands-on_ex/hands-on_ex_01.qmd
    - id: inclass
      title: "In-class Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        href: in-class_ex/in-class_ex_01.qmd
    - id: takehome
      title: "Take-home Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        href: take-home_ex/take-home_ex_01.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

