project:
  type: website

website:
  title: "ISSS608 Visual Analytics & Applications Coursework<br>by Wilson Tan"
  navbar:
    right:
      - sidebar:handson
      - sidebar:inclass
      - sidebar:takehome
  sidebar:
    - id: handson
      title: "Hands-on Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        - href: hands-on_ex/hands-on_ex_01.qmd
        - href: hands-on_ex/hands-on_ex_02.qmd
        - href: hands-on_ex/hands-on_ex_03.qmd
        - href: hands-on_ex/hands-on_ex_04.qmd
    - id: inclass
      title: "In-class Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        - href: in-class_ex/in-class_ex_01.qmd
        - href: in-class_ex/in-class_ex_02.qmd
        - href: in-class_ex/in-class_ex_03.qmd
        - href: in-class_ex/in-class_ex_04.qmd
        - href: in-class_ex/in-class_ex_05.qmd
        - href: in-class_ex/in-class_ex_06.qmd
        - href: in-class_ex/in-class_ex_07.qmd
    - id: takehome
      title: "Take-home Exercises"
      style: "docked"
      collapse-level: 2
      contents:
        - href: take-home_ex/take-home_ex_01.qmd
        - href: take-home_ex/take-home_ex_02.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full

editor: visual

