---
title: "About Me"
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/wilson-tan-88141a253/
    - icon: github
      text: Github
      href: https://www.github.com/wxxtan
---

Wilson is currently working at the Housing & Development Board as a Senior Business Analyst. He is part of the Data Science Team under the Board's Estate Administration & Property Group. This is his job by day.

By night, he transforms into a part-time student pursuing a Master of Information Technology in Business at Singapore Management University. Beyond that, what little pockets of free time left is spent picking up tennis.

## Education

**Singapore Management University**

Master of Information Technology in Business \| Aug 2021 - Present

**National University of Singapore**

B. Soc. Sci in Economics with Honours (Highest Distinction) \| Aug 2014 - Jul 2018

Published Honour's Thesis: *Did the ASEAN-China Free Trade Area Actually Increase ASEAN Countries' Exports to China?*

## Experience

**Housing & Development Board** \| Senior Business Analyst \| Sep 2018 - present
